# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-29 17:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_room', '0002_auto_20180729_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='classes',
            field=models.ManyToManyField(blank=True, to='class_room.Class'),
        ),
        migrations.AlterField(
            model_name='user',
            name='parents',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
