# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-31 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class_room', '0003_auto_20180729_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='classes',
        ),
        migrations.AddField(
            model_name='user',
            name='user_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='class_room.Class'),
        ),
    ]
